export const interests = [
  {
    name: "football",
    category: "sports",
    location: "New York City",
    members: 10,
    image:
      "https://firebasestorage.googleapis.com/v0/b/places-e6047.appspot.com/o/interest_images%2Ffootball.png?alt=media&token=dd81c0bd-952c-4990-8253-0bc08f7dc40b",
  },
  {
    name: "baseball",
    category: "buy/sell",
    location: "New York City",
    members: 150,
    image: "/assets/interest_images/baseball.png",
  },
  {
    name: "basketball",
    category: "donations",
    location: "New York City",
    members: 115,
    image: "/assets/interest_images/basketball.png",
  },
  {
    name: "boxing",
    category: "hobbies",
    location: "New York City",
    members: 3,
    image: "/assets/interest_images/boxing.png",
  },
  {
    name: "climbing",
    category: "sports",
    location: "New York City",
    members: 7,
    image: "/assets/interest_images/climbing.png",
  },
  {
    name: "cycling",
    category: "buy/sell",
    location: "New York City",
    members: 1500,
    image: "/assets/interest_images/cycling.png",
  },
  {
    name: "golf",
    category: "donations",
    location: "New York City",
    members: 68,
    image: "/assets/interest_images/golf.png",
  },
  {
    name: "gymnastics",
    category: "hobbies",
    location: "New York City",
    members: 9,
    image:
      "https://firebasestorage.googleapis.com/v0/b/places-e6047.appspot.com/o/interest_images%2Fgymnastics.png?alt=media&token=d82e27b4-d5cb-41c8-9af3-5a572a63e1a3",
  },
  {
    name: "hockey",
    category: "sports",
    location: "New York City",
    members: 100,
    image: "/assets/interest_images/hockey.png",
  },
  {
    name: "skateboarding",
    category: "buy/sell",
    location: "New York City",
    members: 151,
    image: "/assets/interest_images/skateboarding.png",
  },
  {
    name: "skiing",
    category: "donations",
    location: "New York City",
    members: 15,
    image: "/assets/interest_images/skiing.png",
  },
  {
    name: "rugby",
    category: "hobbies",
    location: "New York City",
    members: 35,
    image: "/assets/interest_images/rugby.png",
  },
  {
    name: "soccer",
    category: "sports",
    location: "New York City",
    members: 68,
    image: "/assets/interest_images/soccer.png",
  },
  {
    name: "surfing",
    category: "buy/sell",
    location: "New York City",
    members: 82,
    image: "/assets/interest_images/surfing.png",
  },
  {
    name: "swimming",
    category: "donations",
    location: "New York City",
    members: 99,
    image: "/assets/interest_images/swimming.png",
  },
  {
    name: "volleyball",
    category: "hobbies",
    location: "New York City",
    members: 1000,
    image: "/assets/interest_images/volleyball.png",
  },
];
