export default {
  English: {
    "0001": "Welcome to Places!",
    "0002": "Discover. Meet. Belong.",
    "0003": "Create an account",
    already_have_an_account: "Already have an account?",
    "0005": "Sign up",
    "0006": "Email",
    "0007": "Password",
    "0008": "Continue",
    "0009": "Or",
    "0010": "Continue with Apple",
    "0011": "Continue with Google",
    "0012": "Continue with Facebook",
    "0013": "Need to create an account?",
    "0014": "Invalid email address, please check.",
    your_password_must_be_at_least_6_characters:
      "Your password must be at least 6 characters.",
    "0016": "Log in",
    "0017": "Create Account",
    "0018": "Choose a Location",
    "0019": "back",
    "0020":
      "Please provide your location so we can display groups for you to join in your area",
    "0021": "Interests",
    "0022": "Skip",
    "0023":
      "Select some interests and we will add you to the group chat(places) for the location you have provided in the previous step",
    "0024": "SPORTS",
    "0025": "HOBBIES",
    "0026": "Join a new place",
    "0027": "+  Join a New Place",
    "0028": "Categories",
    "0029": "Sports",
    "0030": "Buy/Sell",
    "0031": "Donations",
    "0032": "Hobbies",
    "0033": "Join a Place",
    "0034": "Logout",
    "0035": "Facebook",
    "0036": "Log in to use your Facebook account with Places.",
    incorrect_password: "Incorrect Password",
    too_many_attempts_try_again_later:
      "Too many attempts. Please try again later",
    user_not_found: "User not found",
    services: "Services",
    add_a_city: "Add a City",
  },
};
